# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0
  aws-cli: circleci/aws-cli@4.1.3
  # vsp-ci: vector-solutions/vsp-ci@1.5.1

parameters:
  # This set of parameters makes it easier to create new services and keep the
  # directories of the monorepo under control from one spot.
  #
  # It is recommended to use these by passing them into commands rather than
  # hard coding values. You also should not use them from inside commands directly,
  # rather you should have command parameters and pass these from the point of use.
  checkout_dir:
    description: Directory where main repository is checked out
    type: string
    default: mfe-demo-spa
  source_dir:
    description: Directory where source code is located
    type: string
    default: mfe-demo-spa
  workspace_dir:
    description: Directory under which all workspace data should be persisted
    type: string
    default: workspace


# Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
# See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
default-node: &default-node
    docker:
       # Specify the version you desire here
       - image: cimg/node:20.15.0
    resource_class: medium

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    <<: *default-node
    steps:
      # Checkout the code as the first step. 
      - checkout
      - run:
          name: Generate .npmrc
          command: |
            cat > ~/.npmrc \<< EOF
            @vector-web-components:registry=https://livesafe.jfrog.io/artifactory/api/npm/vector-npm/
            //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:_password=${VECTOR_NPM_PASSWORD}
            //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:username=${VECTOR_NPM_USERNAME}
            //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:email=${VECTOR_NPM_EMAIL}
            //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:always-auth=true
            EOF
      # Installs dependencies using CirclCI orb.   
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          # Validate commit message.
          command: echo "$COMMIT_MESSAGE" | npx commitlint
      - run:
          name: Prettier formatting check
          # Check for code formatting issues.
          command: npm run prettier:check
      - run:
          name: Lint changed packages
          # Reduce the linting scope to only changed files, which speeds up the pipeline.
          command: npm run lint -- --since
      - run:
          name: Test changed  packages
          # Run tests and show coverage percentage.
          command: npm test --coverage
      - run:
          name: Build packages
          # Limit the build process to only changed files, which reduces build time.
          command: npm run build -- --since
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >>]
          steps:
            # Clear destination if it is main branch and update version.
            - run:
                name: Clear dist
                command: |
                  if [-d "dist"]; then
                    rm -r dist
                  fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  update-versions:
    <<: *default-node
    steps:
      - attach_workspace:
          at: .
      # Skip version update if current branch is not main branch.
      - unless:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "Skip version update"
            - persist_to_workspace:
                root: .
                paths:
                  - .
      # Update version if current branch is main branch.            
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - add_ssh_keys:
                fingerprints:
                  - 'SHA256:jsNiP0mojRn/PkH9OW2r1gpfFEOU/HRcUj7Pc8PrVo8'
            - run:
                name: Configure git
                command: |
                  git config --global user.name "$GITHUB_ACTOR"
                  git config --global user.email "$GITHUB_EMAIL"
                  mkdir -p ~/.ssh
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
            - run:
                name: Define environment variable with current commit hash before version commit
                command: |
                  set -e
                  commit_hash=$(git rev-parse --short HEAD)
                  echo "export COMMIT_HASH='$commit_hash'" >> $BASH_ENV
            - run:
                name: Version Packages
                command: |
                  timeout 30 npm run lerna -- version -y || true
                  echo "Finished version update"
            - run:
                name: Build with updated versions
                command: npm run build -- --since ${COMMIT_HASH}
            - persist_to_workspace:
                root: .
                paths:
                  - .
  publish-branch-build:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role_arn: "arn:aws:iam::760612481786:role/develop-vector-circleci-cdn-role"
          session_duration: "1800"
          region: "us-east-2"
      - run:
          name: Deploy to S3
          command: |
            if [ -d "dist" ]; then
              ls dist
              aws s3 cp ./dist/ s3://vectorsolutions-web-components-develop/${CIRCLE_PROJECT_REPONAME}-mfe/preview/ --recursive
            else
              echo "No changed packages, skipping publish."
            fi
  publish-dev:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role_arn: "arn:aws:iam::760612481786:role/develop-vector-circleci-cdn-role"
          session_duration: "1800"
          region: "us-east-1"
      - run:
          name: Deploy to dev S3
          command: |
            if [ -d "dist" ]; then
              ls dist
              aws s3 cp ./dist/ s3://vectorsolutions-web-components-develop/${CIRCLE_PROJECT_REPONAME}-mfe/ --recursive
            else
              echo "No changed packages, skipping publish."
            fi
      - run:
          name: Deploy to dev S3 latest folder
          command: |
            if [ -d "dist" ]; then
              # Iterate over all MFE directories in the dist folder
              for MFE_DIR in dist/*; do
                if [ -d "$MFE_DIR" ]; then
                  MFE_NAME=$(basename "$MFE_DIR")
                  echo "Deploying $MFE_NAME"

                  # Find the latest version folder in the current MFE directory
                  LATEST_VERSION_FOLDER=$(ls "$MFE_DIR" | sort -V | tail -n 1)
                  echo "Latest version folder name for $MFE_NAME: $LATEST_VERSION_FOLDER"

                  # Verify the latest version folder exists
                  if [ -d "$MFE_DIR/$LATEST_VERSION_FOLDER" ]; then
                    # Copy the contents of the latest version folder to the 'latest' folder in S3
                    aws s3 cp "$MFE_DIR/$LATEST_VERSION_FOLDER/" s3://vectorsolutions-web-components-develop/${CIRCLE_PROJECT_REPONAME}-mfe/$MFE_NAME/latest/ --recursive
                    echo "Deployed $MFE_NAME to dev S3 latest folder"
                  else
                    echo "Error: Latest version folder does not exist for $MFE_NAME!"
                  fi
                fi
              done
            else
              echo "No changed packages, skipping publish."
            fi  
      - run:
          name: Upload importMap to dev S3
          command: |
            aws s3 cp ./projects/importmap-dev.json s3://vectorsolutions-web-components-develop/${CIRCLE_PROJECT_REPONAME}-mfe/importmap.json
            aws s3 cp ./projects/3rd-party-importmap.json s3://vectorsolutions-web-components-develop/${CIRCLE_PROJECT_REPONAME}-mfe/3rd-party-importmap.json
      - run:
          name: Upload configuration file to dev S3
          command: |
              aws s3 cp ./projects/singlespa-app-config.develop.json s3://vectorsolutions-web-components-develop/${CIRCLE_PROJECT_REPONAME}-mfe/singlespa-app-config.json
      - run:
          name: Invalidate Cloudfront-Dev
          command: |
            aws cloudfront create-invalidation --distribution-id E3NZTUCTOEL6J3  --paths "/${CIRCLE_PROJECT_REPONAME}-mfe/*"
  publish-stage:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role_arn: "arn:aws:iam::760612481786:role/develop-vector-circleci-cdn-role"
          session_duration: "1800"
          region: "us-east-1"
      - run:
          name: Deploy to stage S3
          command: |
            if [ -d "dist" ]; then
              ls dist
              aws s3 cp ./dist/ s3://vectorsolutions-web-components-stage/${CIRCLE_PROJECT_REPONAME}-mfe/ --recursive
            else
              echo "No changed packages, skipping publish."
            fi
      - run:
          name: Deploy to stage S3 latest folder
          command: |
            if [ -d "dist" ]; then
              # Iterate over all MFE directories in the dist folder
              for MFE_DIR in dist/*; do
                if [ -d "$MFE_DIR" ]; then
                  MFE_NAME=$(basename "$MFE_DIR")
                  echo "Deploying $MFE_NAME"

                  # Find the latest version folder in the current MFE directory
                  LATEST_VERSION_FOLDER=$(ls "$MFE_DIR" | sort -V | tail -n 1)
                  echo "Latest version folder name for $MFE_NAME: $LATEST_VERSION_FOLDER"

                  # Verify the latest version folder exists
                  if [ -d "$MFE_DIR/$LATEST_VERSION_FOLDER" ]; then
                    # Copy the contents of the latest version folder to the 'latest' folder in S3
                    aws s3 cp "$MFE_DIR/$LATEST_VERSION_FOLDER/" s3://vectorsolutions-web-components-stage/${CIRCLE_PROJECT_REPONAME}-mfe/$MFE_NAME/latest/ --recursive
                    echo "Deployed $MFE_NAME to stage S3 latest folder"
                  else
                    echo "Error: Latest version folder does not exist for $MFE_NAME!"
                  fi
                fi
              done
            else
              echo "No changed packages, skipping publish."
            fi
      - run:
          name: Upload importMap to stage S3
          command: |
            if git diff --name-only $CIRCLE_BRANCH origin/main | grep -q 'projects/importmap-stage.json'; then
              aws s3 cp ./projects/importmap-stage.json s3://vectorsolutions-web-components-stage/${CIRCLE_PROJECT_REPONAME}-mfe/importmap.json
            fi
            if git diff --name-only $CIRCLE_BRANCH origin/main | grep -q 'projects/3rd-party-importmap.json'; then
              aws s3 cp ./projects/3rd-party-importmap.json s3://vectorsolutions-web-components-stage/${CIRCLE_PROJECT_REPONAME}-mfe/3rd-party-importmap.json
            fi
      - run:
          name: Upload configuration file to stage S3
          command: |
              aws s3 cp ./projects/singlespa-app-config.staging.json s3://vectorsolutions-web-components-stage/${CIRCLE_PROJECT_REPONAME}-mfe/singlespa-app-config.json      
      - run:
          name: Invalidate Cloudfront-Dev
          command: |
            aws cloudfront create-invalidation --distribution-id E3NZTUCTOEL6J3  --paths "/${CIRCLE_PROJECT_REPONAME}-mfe/*"
  publish-prod:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role_arn: "arn:aws:iam::760612481786:role/develop-vector-circleci-cdn-role"
          session_duration: "1800"
          region: "us-east-1"
      - run:
          name: Deploy to prod S3
          command: |
            if [ -d "dist" ]; then
              ls dist
              aws s3 cp ./dist/ s3://vectorsolutions-web-components-prod/${CIRCLE_PROJECT_REPONAME}-mfe/ --recursive
            else
              echo "No changed packages, skipping publish."
            fi
      - run:
          name: Deploy to prod S3 latest folder
          command: |
            if [ -d "dist" ]; then
              # Iterate over all MFE directories in the dist folder
              for MFE_DIR in dist/*; do
                if [ -d "$MFE_DIR" ]; then
                  MFE_NAME=$(basename "$MFE_DIR")
                  echo "Deploying $MFE_NAME"

                  # Find the latest version folder in the current MFE directory
                  LATEST_VERSION_FOLDER=$(ls "$MFE_DIR" | sort -V | tail -n 1)
                  echo "Latest version folder name for $MFE_NAME: $LATEST_VERSION_FOLDER"

                  # Verify the latest version folder exists
                  if [ -d "$MFE_DIR/$LATEST_VERSION_FOLDER" ]; then
                    # Copy the contents of the latest version folder to the 'latest' folder in S3
                    aws s3 cp "$MFE_DIR/$LATEST_VERSION_FOLDER/" s3://vectorsolutions-web-components-prod/${CIRCLE_PROJECT_REPONAME}-mfe/$MFE_NAME/latest/ --recursive
                    echo "Deployed $MFE_NAME to prod S3 latest folder"
                  else
                    echo "Error: Latest version folder does not exist for $MFE_NAME!"
                  fi
                fi
              done
            else
              echo "No changed packages, skipping publish."
            fi
      - run:
          name: Upload importMap to prod S3
          command: |
            if git diff --name-only $CIRCLE_BRANCH origin/main | grep -q 'projects/importmap-prod.json'; then
              aws s3 cp ./projects/importmap-prod.json s3://vectorsolutions-web-components-prod/${CIRCLE_PROJECT_REPONAME}-mfe/importmap.json
            fi
            if git diff --name-only $CIRCLE_BRANCH origin/main | grep -q 'projects/3rd-party-importmap.json'; then  
              aws s3 cp ./projects/3rd-party-importmap.json s3://vectorsolutions-web-components-prod/${CIRCLE_PROJECT_REPONAME}-mfe/3rd-party-importmap.json
            fi
      - run:
          name: Upload configuration file to prod S3
          command: |
              aws s3 cp ./projects/singlespa-app-config.production.json s3://vectorsolutions-web-components-prod/${CIRCLE_PROJECT_REPONAME}-mfe/singlespa-app-config.json       
      - run:
          name: Invalidate Cloudfront-Dev
          command: |
            aws cloudfront create-invalidation --distribution-id E3NZTUCTOEL6J3  --paths "/${CIRCLE_PROJECT_REPONAME}-mfe/*"                             
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  feature-build:
    when:
      not:
        equal: [ "main", << pipeline.git.branch >> ]
    jobs:
      # - vsp-ci/scan-code:
      #     name: mfe-demo Code Scan
      #     context:
      #       - VeracodeAgents
      #     pre_steps:
      #     - run:
      #         name: Generate .npmrc
      #         working_directory: .
      #         command: |
      #           cat > ~/.npmrc \<< EOF
      #           @vector-solutions:registry=https://livesafe.jfrog.io/artifactory/api/npm/vector-npm/
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:_password=${VECTOR_NPM_PASSWORD}
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:username=${VECTOR_NPM_USERNAME}
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:email=${VECTOR_NPM_EMAIL}
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:always-auth=true
      #           EOF
      #     checkout_dir: << pipeline.parameters.checkout_dir >>
      #     working_directory: << pipeline.parameters.source_dir >>
      #     workspace_dir: .
      #     project_name: example
      #     project_path: .
      #     veracode_agent_api_var: VTP_VERACODE_SCAN_AGENT_API
      #     veracode_dev_branch_agent_api_var: VTP_DEV_BRANCH_VERACODE_SCAN_AGENT_API
      #     docker_image: node:16
      #     git_branch: << pipeline.git.branch >>
      #     veracode_risk_level: Medium
      #     veracode_acceptable_medium_risk_level_count: 1
      - build-and-test:
          context:
            - Vector NPM
            - Vector CI Bot GitHub
          # requires:
          #   # - mfe-demo
      - publish-branch-build:
          requires:
            - build-and-test
            # - mfe-demo
  full-build:
    when:
      equal: [ "main", << pipeline.git.branch >> ]
    jobs:
      # - vsp-ci/scan-code:
      #     name: mfe-demo Code Scan
      #     context:
      #       - VeracodeAgents
      #     pre_steps:
      #     - run:
      #         name: Generate .npmrc
      #         working_directory: .
      #         command: |
      #           cat > ~/.npmrc \<< EOF
      #           @vector-solutions:registry=https://livesafe.jfrog.io/artifactory/api/npm/vector-npm/
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:_password=${VECTOR_NPM_PASSWORD}
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:username=${VECTOR_NPM_USERNAME}
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:email=${VECTOR_NPM_EMAIL}
      #           //livesafe.jfrog.io/artifactory/api/npm/vector-npm/:always-auth=true
      #           EOF
      #     checkout_dir: << pipeline.parameters.checkout_dir >>
      #     working_directory: << pipeline.parameters.source_dir >>
      #     workspace_dir: .
      #     project_name: example
      #     project_path: .
      #     veracode_agent_api_var: VTP_VERACODE_SCAN_AGENT_API
      #     veracode_dev_branch_agent_api_var: VTP_DEV_BRANCH_VERACODE_SCAN_AGENT_API
      #     docker_image: node:16
      #     git_branch: << pipeline.git.branch >>
      #     veracode_risk_level: Medium
      #     veracode_acceptable_medium_risk_level_count: 1
      - build-and-test:
          context:
            - Vector NPM
            - Vector CI Bot GitHub
          # requires:
          #   - mfe-demo
      - update-versions:
          context:
            - Vector CI Bot GitHub
          requires:
            - build-and-test
            # - mfe-demo
      - publish-dev:
          requires:
            - update-versions 
            - build-and-test
            # - mfe-demo
      # - approval:
      #     type: approval
      #     name: Approve for promoting to Stage
      #     requires:
      #       - publish-dev
      # - publish-stage:
      #     requires:
      #       - Approve for promoting to Stage
      # - approval:
      #     type: approval
      #     name: Approve for promoting to Prod
      #     requires:
      #       - publish-stage
      # - publish-prod:
      #     requires:
      #       - Approve for promoting to Prod